---
title: "Ebola Forecasting - Important Figures"
author: "Andy Shen"
date: "9/9/2020"
output: 
  pdf_document:
    number_sections: true
---

```{r, include = FALSE}
## Complete Outbreak Dataset 
## Used to plot the true number of infections over time
rm(list=ls())
true <- read.csv("/Volumes/GoogleDrive/.shortcut-targets-by-id/15UGkfREtfqH3LdfHmCsSpFJ5SrTnSeyt/ebola/2020-05-04_ebola/2020-05-04_data.csv")
source("outbreak_vis.R") #script with functions
rgx <- "\\d{1,2}\\/\\d{1,2}\\/\\d{4}" #date structure regex
true <- true[str_detect(true$Date, rgx),] #omits rows without a date
colnames(true) <- c("date", "cases")
true$date <- mdy(true$date) #converts into a consistent date format
true$cases[is.na(true$cases)] <- 0
true <- true %>% mutate(total = cumsum(cases))
last_date <- true$date[length(true$date)]
last_case <- true$total[length(true$total)]
```

```{r, include = FALSE}
## Recursive Projections Dataset
rproj <- read.csv("/Volumes/GoogleDrive/.shortcut-targets-by-id/1LaD1nL_OAOposW2fr2XDcs6BLHVBC-jA/2019 Ebola/Post-Outbreak Analysis/recursive_post_proj.csv") #forecasted values
rproj <- rproj %>% select(date_last_case, pred.7, pred.14, pred.21) 
rproj$date_last_case <- mdy(rproj$date_last_case)
rproj <- na.omit(rproj) # some dates have no projections
rdates <- as.character(rproj$date_last_case)
rpreds <- t(rproj %>% select(pred.7,pred.14,pred.21))
omit_h <- c(8,17,22,33,47:49,51,52,55,56,60,64,69,77) #omit from Hawkes because Recursive has no data for these dates
```

```{r, include = FALSE}
## Hawkes Projections Dataset
hproj <- read.csv("/Volumes/GoogleDrive/.shortcut-targets-by-id/1LaD1nL_OAOposW2fr2XDcs6BLHVBC-jA/2019 Ebola/Post-Outbreak Analysis/hawkes_post_proj.csv") #forecasted values
hproj <- hproj %>% select(date_last_case, pred.7, pred.14, pred.21) #selecting only the cols with forecasts
hproj$date_last_case <- mdy(hproj$date_last_case)
hproj <- hproj[-omit_h,] #omit the rows that aren't also in recursive
hdates <- as.character(hproj$date_last_case) #for working with dates
hpreds <- t(hproj %>% select(pred.7,pred.14,pred.21)) #take t() for the function
rownames(hproj) <- 1:nrow(hproj)
```


# Dataset Selection

```{r}
hr3 <- c("2018-08-26","2019-07-26","2020-02-06")
```

```{r}
indh <- indr <- c(2,149,161) #corresponding indices for above dates
print(hpreds3 <- hpreds[,indh])
print(rpreds3 <- rpreds[,indr])
```

\pagebreak

# Full Outbreak

```{r}
ggplot(
  data = true,
  mapping = aes(x = date, y = total)
) + geom_line() + theme_light()
```

# New Cases by Day

```{r}
true <- true %>% mutate(seven_day_avg = zoo::rollmean(cases, k = 7,fill = NA))
```



```{r,warning=FALSE}
title <- paste0("Ebola Cases by Day in West Africa with 7-day Rolling Average")
ggplot(
  data = true,
  mapping = aes(x = date, y = cases)
) + geom_col(color = "lightblue") + theme_light() + 
  geom_path(
    data = true, 
    mapping = aes(x = date, y = seven_day_avg),
    color = "black"
  ) + labs(title = title) + theme(legend.position = "bottom")
```

\pagebreak

# Hawkes Forecasts

## Hawkes 7-Day

```{r}
print(h7 <- single_forecast(hr3, hpreds3, days = 7, point = T))
```

\pagebreak

## Hawkes 14-Day

```{r}
print(h14 <- single_forecast(hr3, hpreds3, days = 14, point = T))
```

\pagebreak

## Hawkes 21-Day

```{r}
print(h21 <- single_forecast(hr3, hpreds3, days = 21, point = T))
```


\pagebreak

# Recursive Forecasts

## Recursive 7-Day

```{r}
print(r7 <- single_forecast(hr3, rpreds3, days = 7, point = T))
```

\pagebreak

## Recursive 14-Day

```{r}
print(r14 <- single_forecast(hr3, rpreds3, days = 14, point = T))
```

\pagebreak

## Recursive 21-Day

```{r}
print(r21 <- single_forecast(hr3, rpreds3, days = 21, point = T))
```

\pagebreak

# RMSE

```{r,echo=FALSE}
caption <- paste0("RMSE values for 3 selected datasets.")
df_rmse <- data.frame(
  "Hawkes" = c(h7$rmse, h14$rmse, h21$rmse),
  "Recursive" = c(r7$rmse, r14$rmse, r21$rmse)
)
row.names(df_rmse) <- c("7-day","14-day","21-day")
tbl1<-df_rmse %>% knitr::kable(digits = 2, caption = caption) 
tbl1
```

