---
title: "Ebola Forecasting - Residual Analysis"
author: "Andy Shen"
date: "9/11/2020"
output: 
  pdf_document:
    number_sections: true
---

```{r, include = FALSE}
## Complete Outbreak Dataset 
## Used to plot the true number of infections over time
rm(list=ls())
true <- read.csv("/Volumes/GoogleDrive/.shortcut-targets-by-id/15UGkfREtfqH3LdfHmCsSpFJ5SrTnSeyt/ebola/2020-05-04_ebola/2020-05-04_data.csv")
source("outbreak_vis.R") #script with functions
rgx <- "\\d{1,2}\\/\\d{1,2}\\/\\d{4}" #date structure regex
true <- true[str_detect(true$Date, rgx),] #omits rows without a date
colnames(true) <- c("date", "cases")
true$date <- mdy(true$date) #converts into a consistent date format
true$cases[is.na(true$cases)] <- 0
true <- true %>% mutate(total = cumsum(cases))
last_date <- true$date[length(true$date)]
last_case <- true$total[length(true$total)]
```

```{r, include = FALSE}
## Recursive Projections Dataset
rproj <- read.csv("/Volumes/GoogleDrive/.shortcut-targets-by-id/1LaD1nL_OAOposW2fr2XDcs6BLHVBC-jA/2019 Ebola/Post-Outbreak Analysis/recursive_post_proj.csv") #forecasted values
rproj <- rproj %>% select(date_last_case, pred.7, pred.14, pred.21) 
rproj$date_last_case <- mdy(rproj$date_last_case)
rproj <- na.omit(rproj) # some dates have no projections
#rproj <- rproj %>% distinct()
rownames(rproj) <- 1:nrow(rproj)
rdates <- as.character(rproj$date_last_case)
rpreds <- t(rproj %>% select(pred.7,pred.14,pred.21))
omit_h <- c(8,17,22,33,47:49,51,52,55,56,60,64,69,77) #omit from Hawkes because Recursive has no data for these dates
```

```{r, include = FALSE}
## Hawkes Projections Dataset
hproj <- read.csv("/Volumes/GoogleDrive/.shortcut-targets-by-id/1LaD1nL_OAOposW2fr2XDcs6BLHVBC-jA/2019 Ebola/Post-Outbreak Analysis/hawkes_post_proj.csv") #forecasted values
hproj <- hproj %>% select(date_last_case, pred.7, pred.14, pred.21) #selecting only the cols with forecasts
hproj$date_last_case <- mdy(hproj$date_last_case)
hproj <- hproj[-omit_h,] #omit the rows that aren't also in recursive
#hproj <- hproj %>% distinct()
hdates <- as.character(hproj$date_last_case) #for working with dates
hpreds <- t(hproj %>% select(pred.7,pred.14,pred.21)) #take t() for the function
rownames(hproj) <- 1:nrow(hproj)
```

# Full Outbreak

```{r}
title <- paste0("Cumulative Ebola Cases by Day in West Africa")
overall <- ggplot(
  data = true,
  mapping = aes(x = date, y = total)) + 
  geom_line() + theme_light() + labs(caption = title) + 
  theme(plot.caption = element_text(hjust = 0.5)) +
  scale_x_date(date_breaks = "5 months", date_labels = "%b-%y")
overall #+ theme(panel.grid.minor = element_blank())
#ggsave("test.png",p,width = 6, height = 4, units="in")
```


# Residual Analysis

## With ggplot

```{r}
cap <- paste0("Residual plot of Hawkes and Recursive 7-day models")
h7 <- (single_forecast(hdates, hpreds, days = 7)$results)
r7 <- (single_forecast(rdates, rpreds, days = 7)$results)
df <- data.frame(
  date = h7$forecast.date,
  hawkes = h7$resids,
  recursive = r7$resids
)
df <- pivot_longer(df, cols = 2:3, names_to = "type", values_to = "resid")
p <- ggplot(
  data = true,
  mapping = aes(x = date, y = total)
) + 
  theme_bw() + labs(caption = cap) + 
  theme(plot.caption = element_text(hjust = 0.5), legend.position = "bottom") +
  scale_x_date(date_breaks = "5 months", date_labels = "%b-%y") + 
  geom_hline(aes(yintercept=0))
  
p + geom_point(
  data = df,
  mapping = aes(x = as.Date(date), y = resid, color = type)
)
```

\pagebreak



